#!/usr/bin/env Rscript

###### 
# This script will generate a mapping file for the ChimpTerm study.
# ./make_mapping_file_chimp_term.R 
# input: 	chimp poo log in tsv
#			termite log in tsv
#			list of sequencing names from folder
# output: 	mapping_file_ChimpTerm.txt
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### Things to read in:
chimp_log_file <- "../data/logs/chimp_poo_log_2017_01_24ERD.tsv"
term_log_file <- "../data/logs/termite_log_2017-01-24ERD.tsv"
sample_path <- "../data/raw/sequencing_data/JA16414/"

chimp_log <- read.table(chimp_log_file, sep="\t", header=TRUE, stringsAsFactors=FALSE)
term_log <- read.table(term_log_file, sep="\t", header=TRUE, stringsAsFactors=FALSE)
samples <- list.files(sample_path, pattern="*_L001_R1_001.fastq.gz$")
samples <- gsub("_L001_R1_001.fastq.gz", "", samples)



##### Create mapping file:
# Fill out columns in the two tables
term_log$Nest <- NA
term_log$nest_group <- NA
term_log$low_concentration <- NA
term_log$nest_ID <- NA

chimp_log$Text <- NA
chimp_log$mound <- NA
chimp_log$weight..g. <- NA

# Make sure column names match exactly
colnames(term_log)[which(colnames(term_log) == "DNA.ID")] <- "DNA.Extraction.ID"
colnames(chimp_log)[which(colnames(chimp_log) == "ng.ul")] <- "ng.uL"

# reorder chimp table to match termite table, add sample type column, and combine into one table:
ind <- match(colnames(term_log), colnames(chimp_log))
chimp_log2 <- chimp_log[,ind]
chimp_log2$sample_type <- "chimp"
term_log$sample_type <- "termite"
log <- rbind(chimp_log2, term_log)

# Add sampleID to table:
log$SampleID <- gsub("_", "-", log$seqID_16S)

# Reorder columns:
log2 <- log[,c("SampleID", 
				"sample_type", 
				"Date", 
				"collector", 
				"mound", 
				"Nest", 
				"nest_group", 
				"nest_ID", 
				"DNA.Extraction.ID", 
				"Date.DNA.extracted", 
				"ng.uL", 
				"A260.280", 
				"A260.230", 
				"weight..g.", 
				"comment", 
				"seqID_16S", 
				"seqID_ITS", 
				"seq_dilution_uL_sample", 
				"seq_dilution_uL_water", 
				"concentration_sent_for_sequencing",
				"volume_sent_for_sequencing", 
				"date_sent_for_sequencing", 
				"low_concentration",
				"Text",
				"Sample"
			)] 
			
# Make column names uniform:
colnames(log2)[c(3,6,9,10,14,24,25)] <- c("date_collected", "nest", "DNA_extraction_ID", "date_DNA_extracted", "weight_g", "text", "sample_name_on_tube")



##### Save table:
# Full table:
write.table(log2, "../data/processed/QIIME/mapping_file_ChimpTerm_full.txt", sep="\t", row.names=FALSE, quote=FALSE)

# Only samples with sequencing data:
log3 <- log2[-which(is.na(log2$SampleID)),]
write.table(log3, "../data/processed/QIIME/mapping_file_ChimpTerm_sequenced_only.txt", sep="\t", row.names=FALSE, quote=FALSE)

print("DONE!")