#!/usr/bin/env Rscript

######  
suppressMessages(library("docopt"))
"
Usage: 
	pull_barcode_info_from_sequencing_files.R -h | --help
	pull_barcode_info_from_sequencing_files.R --seq_path=<seq_path> --out=<out>

Description: This script will pull barcode information from sequencing files and output a table that lists the sample name and the barcode. 

Options:
	-h  --help			print arguments to screen
	--seq_path=<seq_path> 		path to where sequencing files are stored
	--out=<out> 				path and filename of table to write out
" -> doc
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### Load arguments:
opts <- docopt(doc)
#print(opts)
seq_path <- opts$seq_path
out <- opts$out


#seq_path <- "../data/raw/sequencing_data/JA16414/"
#out <- "../data/processed/1_general_sample_info/table_barcodes_JA16414.txt"



##### Load libraries:
library("testit")



##### Read in files:
bFiles <- list.files(seq_path, pattern="*_I[1]_001.fastq.gz$")

# Create a list of sample IDs with the sequencing center ID included:
sequencingID <- sapply(bFiles, function(x) {strsplit(x, split="_L001")[[1]][1]})

# Create a list of sampleIDs:
sampleID <- sapply(bFiles, function(x) {strsplit(x, split="_")[[1]][1]})

pull_bc <- function(x) {
	test1 <- read.table(paste0(seq_path, x), sep="\n", header=FALSE, stringsAsFactors=FALSE)
	# Find most common barcode:
	bcs <- test1$V1[seq(2, dim(test1)[1], by=4)]
	bc <- names(sort(table(bcs), decreasing=TRUE))[1]
	bc_count <- sort(table(bcs), decreasing=TRUE)[1]
	demultiplexed <- length(bcs)
	returnme <- c(bc, demultiplexed, bc_count)
}

output <- data.frame(sapply(bFiles, pull_bc))
output <- cbind(bFiles, sequencingID, sampleID, t(output))
colnames(output) <- c("file_name", "sequencingID", "sampleID", "barcode", "total_reads", "reads_perfect_match")

write.table(output, out, sep="\t", row.names=FALSE, quote=FALSE)


print("DONE!")