#!/usr/bin/env Rscript

###### 
# This script will output a shell script that will generate mini mapping files and run split_library_fastq.py for all samples from JA16414. 
# This script should be run on the cluster so that it can output the mapping files correctly. 
# ./split_libraries_fastq_JA16414.R 
# input: 	list of files to merge
# output: 	shell script to run split_libraries
#			mapping files for each sample
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### List files in directory:
bFiles <- list.files("../data/raw/sequencing_data/JA16414/", pattern="*_I[1]_001.fastq.gz$")

# Get list of sequencingIDs:
sequencingID <- sapply(bFiles, function(x) {strsplit(x, split="_L001")[[1]][1]})



##### Generate mapping files for split_by_library_fastq.py step:
print("generating mapping files for split_libraries_fastq.py")
# Set up base mapping file:
mfile <- matrix("", nrow=1, ncol=4)
colnames(mfile) <- c("#SampleID", "BarcodeSequence", "LinkerPrimerSequence", "Description")

# Where to store mapping files:
outpath <- "../data/processed/QIIME/1_join_paired_ends/"

for (i in 1:length(bFiles)) {
	mfile[1,c(1,4)] <- sequencingID[i]
	
	op <- paste0(outpath, sequencingID[i], "/")
	write.table(mfile, paste0(op, "mapping_file.txt"), sep="\t", quote=FALSE, row.names=FALSE)
}
	


##### Generate a script to run split_by_library_fastq.py on all samples individually:
print("writing split_by_library_JA16414.sh")

script <- c("#!/bin/bash")
script <- c(script, "source qiime_bash")

outpath <- "../data/processed/QIIME/2_split_libraries/"
inpath <- "../data/processed/QIIME/1_join_paired_ends/"

for (i in 1:length(bFiles)) {
	no <- paste0(outpath, sequencingID[i],"/") # Create new out path where folder is labeled by sample ID
	ip <- paste0(inpath, sequencingID[i],"/") # In path for individual sample folders
	script <- c(script, paste0("mkdir ", no))
	script <- c(script, paste0("split_libraries_fastq.py -i ", ip, "fastqjoin.join.fastq -o ", no, " -m ", ip, "mapping_file.txt -q 25 --barcode_type not-barcoded --sample_ids ", sequencingID[i]))
}

# Write out join paired end script:
write.table(script, "split_by_library_JA16414.sh", sep="\n", quote=FALSE, col.names=FALSE, row.names=FALSE)


print("DONE!")
