#!/usr/bin/env Rscript

###### 
# This script will output a table and a barplot of the number of reads sequenced per sample. 
# ./summarize_reads_per_sample.R 
# input: 	txt file of reads in fastq files
# output: 	text file containing reads per sample
#			barplot of the reads per sample
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### Read in data:
ja14814 <- read.table("../results/2_general_info/reads_per_file_original_demultiplexed_JA14814_fastq_2016-08-03.txt", sep="\t", header=FALSE, stringsAsFactors=FALSE)



##### Create table:
# Pull one file per sample:
reads <- ja14814[seq(1, nrow(ja14814), by=4),]

# Reformat sample name:
reads$V1 <- sapply(reads$V1, function(x) {strsplit(x, split="_")[[1]][1]})

# Add column names:
colnames(reads) <- c("sample", "reads")

# Save table:
write.table(reads, paste0("../results/2_general_info/reads_per_sample_original_demultiplexed_JA14814_", today,"ERD.txt"), sep="\t", quote=FALSE, row.names=FALSE)



##### Plot it up:
# Function for plotting chimp/termite colors:
col.me <- function(x) {
	if (grepl("-C-", x)) {
		return("blue")
	} else if (grepl("-T-", x)) {
		return("tomato")
	}
}

# Sort samples by number of reads:
sreads <- reads[order(reads$reads),]

# Get stats:
myMean <- mean(reads$reads)
chimpMean <- mean(reads$reads[grepl("-C-", reads$sample)])
termiteMean <- mean(reads$reads[grepl("-T-", reads$sample)])

# Barchart:
pdf(paste0("../results/2_general_info/barplot_reads_per_sample_original_demultiplexed_JA14814_", today,"ERD.pdf"), width=8, height=6)
p <- barplot(sreads$reads, col=sapply(sreads$sample, col.me), main="Reads sequenced per sample", xlab="sample", ylab="reads", space=0)
legend("topleft", col=c("blue", "tomato", "gray", "blue", "tomato"), lty=c(NA, NA, 1,1,1), pch=c(15, 15, NA, NA, NA), legend=c("Chimp", "Termite", "mean reads (all samples)", "mean reads (chimps)", "mean reads, (termites)"), bty="n")
abline(h=c(myMean, chimpMean, termiteMean), col=c("gray", "blue", "tomato"))
text(x = dim(sreads)[1]+1.2, y=c(myMean, termiteMean), labels=round(c(myMean, termiteMean), 0), las=3, col=c("gray", "tomato"), xpd=TRUE, pos=3)
text(x = dim(sreads)[1]+1.2, y=chimpMean, labels=round(chimpMean, 0), las=3, col=c("blue"), xpd=TRUE, pos=1)
litter <- dev.off()



print("DONE!")